/* PREVIEW BUILD ONLY — not part of the repo, generated by tools/build-preview.sh.
 *
 * Stands in for assets/js/gate.js so hosted previews open straight onto the
 * site. It is a copy of the real gate.js's already-unlocked branch: the same
 * reveal(), run at the same point in the document. Nothing else is touched,
 * so what you see below the gate is exactly what the real build renders.
 */
(function () {
  "use strict";
  var root = document.documentElement;
  // Set before first paint by the inline script in the layout; the real
  // gate.js clears it here too.
  root.classList.remove("gate-locked");
  var overlay = document.getElementById("preview-gate");
  if (overlay) overlay.remove();
  window.dispatchEvent(new CustomEvent("gate:unlocked"));
})();
